[tool.poetry]
name = "github-readme-terminal"
version = "0.0.3"
description = "✨ Elevate your GitHub Profile ReadMe with Minimalistic Retro Terminal GIFs 🚀"
authors = ["Avishek Sen <x0rzavi@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/x0rzavi/github-readme-terminal"
packages = [
    { include = "gifos" }
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/x0rzavi/github-readme-terminal/issues"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
Pillow = "==12.0.0"

[tool.poetry.group.docs.dependencies]
docformatter = "^1.7.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
